version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD= admin
      - MYSQL_DATABASE= ysl
      - MYSQL_USER= Admin
      - MYSQL_PASSWORD= 151617_Wahyu
    networks:
      backend:
        aliases:
          - db
  app:
    build:
      context: '.'
      dockerfile: Dockerfile
    container_name: webysl-php
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      backend:
        aliases:
          - webyslphp

networks:
  backend:
    name: backend-network